name: ci

on:
  push: 
    paths:
      - src/**
    branches:
      - main

jobs:
  docker:
    runs-on: self-hosted
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set 6-char SHA as Env Variable
        run: echo "COMMIT_ID=${GITHUB_SHA::6}" >> $GITHUB_ENV
        
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      -
        name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: zavazan/python-app:${{ env.COMMIT_ID }}
